# Travis CI configuration

language: php

dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: vendor/bin/phpunit